name: Deploy Army Checkup App

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest

    env:
      LIGHTSAIL_INSTANCE_IP: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
      SSH_USERNAME: ubuntu
      APP_NAME: army-checkup-backend
      ENV_FILE_PATH: /home/ubuntu/army-checkup/.env/.env.production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ env.LIGHTSAIL_INSTANCE_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Backend to Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.LIGHTSAIL_INSTANCE_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Install git if not installed
            if ! command -v git &> /dev/null; then
              sudo apt-get update && sudo apt-get install -y git
            fi

            # Remove existing backend directory if it exists
            rm -rf /home/ubuntu/army-checkup/backend

            # Clone the latest code from GitHub
            git clone ${{ github.server_url }}/${{ github.repository }}.git /home/ubuntu/army-checkup/temp

            # Move backend directory to final location
            mv /home/ubuntu/army-checkup/temp/backend /home/ubuntu/army-checkup/
            rm -rf /home/ubuntu/army-checkup/temp

            # Navigate to backend project directory
            cd /home/ubuntu/army-checkup/backend

            # Verify Node.js and npm installation
            node -v || { echo "Node.js not found"; exit 1; }
            npm -v || { echo "npm not found"; exit 1; }

            # Install PM2 globally if not installed
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Install dependencies
            npm install

            # Check if the .env.production file exists, otherwise exit
            echo "Checking if env.production file exists..."
            ls -l /home/ubuntu/army-checkup/.env/

            if [ ! -f ${{ env.ENV_FILE_PATH }} ]; then
              echo ".env.production file not found"
              exit 1
            fi

            # Copy environment file to the current directory
            cp /home/ubuntu/army-checkup/.env/.env.production .env

            # Restart the application with PM2
            pm2 delete ${{ env.APP_NAME }} || true
            pm2 start npm --name ${{ env.APP_NAME }} -- run start
            pm2 save

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: deploy-backend

    env:
      LIGHTSAIL_INSTANCE_IP: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
      SSH_USERNAME: ubuntu
      ENV_FILE_PATH: /home/ubuntu/army-checkup/.env/.env.production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ env.LIGHTSAIL_INSTANCE_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Frontend to Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.LIGHTSAIL_INSTANCE_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create frontend directory if it doesn't exist
            mkdir -p /home/ubuntu/army-checkup/frontend

      - name: Copy Frontend Build
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.LIGHTSAIL_INSTANCE_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/dist/*"
          target: "/home/ubuntu/army-checkup/frontend"
          strip_components: 2
