name: Deploy to AWS Lightsail

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Build and deploy Frontend
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      # Build Backend
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      # Deploy to Lightsail
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > lightsail_key.pem
          chmod 600 lightsail_key.pem

      - name: Deploy to Lightsail
        run: |
          # Create deployment directory
          mkdir -p deploy

          # Package applications
          cd frontend/dist && zip -r ../../deploy/frontend.zip .
          cd ../../backend && zip -r ../deploy/backend.zip .
          cd ..

          # Upload to Lightsail instance
          instance_ip="${{ secrets.LIGHTSAIL_IP }}"

          # Copy files to instance using SCP
          scp -o StrictHostKeyChecking=no \
              -i lightsail_key.pem \
              deploy/frontend.zip deploy/backend.zip \
              bitnami@${instance_ip}:/home/bitnami/apps/

          # Execute deployment commands
          ssh -o StrictHostKeyChecking=no \
              -i lightsail_key.pem \
              bitnami@${instance_ip} \
              "cd /home/bitnami/apps && \
               unzip -o frontend.zip -d frontend && \
               unzip -o backend.zip -d backend && \
               cd backend && npm install && \
               pm2 restart all"

      - name: Cleanup
        run: rm -rf deploy lightsail_key.pem
